pipeline {

  agent any
  tools {
        maven 'Maven 3.9.6'
    }

    stages {
        stage('Install') {
            steps {
                sh 'mvn clean install compile test'
            }
        }
      stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
